apiVersion: v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app1
    spec:
      containers:
        - name: nginx-container1
          image: nginx:1.21.0
          ports:
            - containerPort: 80
          env:
            - name: ENV
              value: production
            - test: TEST
              value: true
            - test: TEST1
              value: true
